name: Upload file
on:
  workflow_dispatch:
    inputs:
      upl:
        description: 'Direct links separated by commas'
        required: true
        type: string
      tag:
        description: 'Tag'
        required: true
        type: string

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Cached APT
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: aria2 gh
          
      - name: Download files
        run: |
          mkdir -p dloa
          IFS=$'\n'
          
          prepare_url() {
            local url="$1"
            
            if [[ ! "$url" =~ ^https?:// ]]; then
              url="https://$url"
            fi

            urls_to_try=("$url")
            if [[ ! "$url" =~ ^https?://www\. ]]; then
              urls_to_try+=("${url/https:\/\//https://www.}")
            fi
            
            echo "${urls_to_try[@]}"
          }

          echo "${{ github.event.inputs.upl }}" | tr ',' '\n' | while read -r url; do
            prepare_url "$url"
          done | tr ' ' '\n' | xargs -n 4 -P 4 -I {} bash -c 'aria2c -d dloa --split=8 --max-connection-per-server=4 --min-split-size=5M --continue=true "$1" && exit 0' _ {}

      - name: Check files in dloa directory
        run: |
          echo "Files in dloa directory:"
          ls -alh dloa/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload files to release
        run: |
          IFS=$'\n'
          ls dloa/* | xargs -n 4 -P 4 -I {} gh release upload "${{ github.event.inputs.tag }}" "{}" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
