name: Upload file
on:
  workflow_dispatch:
    inputs:
      upl:
        description: 'URL file'
        required: true
        type: string
      tag:
        description: 'Tag'
        required: true
        type: string

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: APT update
        run: |
          sudo apt-get update
      - name: Cached APT
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: aria2
      - name: download
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p dloa
          IFS=',' read -r -a urls <<< "${{ inputs.upl }}"
          for url in "${urls[@]}"; do
          aria2c -d dloa -x 16 -s 16 --continue=true "$url" &
          done
          wait
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: dloa/*
          tag_name: ${{ inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
