name: Upload file
on:
  workflow_dispatch:
    inputs:
      upl:
        description: 'Direct links separated by commas'
        required: true
        type: string
      tag:
        description: 'Tag'
        required: true
        type: string

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: Cached APT
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: aria2
          
      - name: Parallel download
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p dloa
          IFS=',' read -r -a urls <<< "${{ github.event.inputs.upl }}"
          for url in "${urls[@]}"; do
            aria2c -d dloa -x 16 -s 16 --continue=true "$url" &
          done
          wait

      - name: Check if release exists
        run: |
          gh release view "${{ github.event.inputs.tag }}" || echo "Release not found"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Create release if it doesn't exist
        run: |
          gh release create "${{ github.event.inputs.tag }}" dloa/* --title "Release for ${{ github.event.inputs.tag }}" --notes "Automated release"
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to release
        run: |
          for file in dloa/*; do
            gh release upload "${{ github.event.inputs.tag }}" "$file" --clobber &
          done
          wait
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
