name: Upload file
on:
  workflow_dispatch:
    inputs:
      upl:
        description: 'Direct links separated by commas'
        required: true
        type: string
      tag:
        description: 'Tag'
        required: true
        type: string

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: APT Update
        run: |
          sudo apt-get update
      - name: Cached APT
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: aria2
          
      - name: Parallel Download and Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p dloa
          IFS=',' read -r -a urls <<< "${{ github.event.inputs.upl }}"
          for url in "${urls[@]}"; do
            aria2c -d dloa -x 16 -s 16 --continue=true "$url" &
          done
          wait
          for file in dloa/*; do
            gh release upload "${{ github.event.inputs.tag }}" "$file" --clobber &
          done
          wait

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
