name: Upload file
on:
  workflow_dispatch:
    inputs:
      upl:
        description: 'Direct links separated by commas'
        required: true
        type: string
      tag:
        description: 'Tag'
        required: true
        type: string

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    steps:

      - name: Cached APT
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: aria2
          
      - name: Download
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p dloa
          IFS=',' read -r -a urls <<< "${{ github.event.inputs.upl }}"
          for url in "${urls[@]}"; do
            aria2c -d dloa -x 16 -s 16 --continue=true "$url" &
          done
          wait
          
      - name: Check files in dloa directory
        run: |
          echo "Files in dloa directory:"
          ls -alh dloa/

  upload:
    runs-on: ubuntu-latest
    needs: download
    strategy:
      matrix:
        file: [dloa/*]
    steps:
      - name: Upload to release in parallel
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: ${{ matrix.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
