name: Download and Extract ISO Files
on:
  workflow_dispatch:
    inputs:
      iso_url:
        description: 'URL of the ISO file to download'
        required: true

permissions:
  contents: write
  packages: write

jobs:
  download_and_extract:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 p7zip-full fuseiso

      - name: Create Download Directory
        run: mkdir -p ${{ github.workspace }}/download

      - name: Download ISO
        run: |
          aria2c "${{ github.event.inputs.iso_url }}" -d ${{ github.workspace }}/download || { echo "Download failed"; exit 1; }
          echo "Downloaded ISO files:"
          find ${{ github.workspace }}/download -name "*.iso"

      - name: Verify Downloaded ISO
        run: |
          ISO_FILE=$(find ${{ github.workspace }}/download -name "*.iso" -type f | head -n 1)
          if [ -z "$ISO_FILE" ]; then
            echo "No ISO file found!"
            exit 1
          fi
          echo "ISO file found: $ISO_FILE"
          echo "ISO file found: $ISO_FILE"
          
          # Calculate CRC32 in hexadecimal format using Python
          echo "Calculating CRC32 checksum for the ISO file..."
          CRC32_CHECKSUM=$(python3 -c "
          import zlib
          import sys

          with open('$ISO_FILE', 'rb') as f:
              file_data = f.read()
              crc32 = zlib.crc32(file_data) & 0xffffffff
              print(hex(crc32)[2:].upper())
          ")
          echo "CRC32 checksum (hex): $CRC32_CHECKSUM"

          EXPECTED_CRC32="EXPECTED_CRC32_VALUE"
            if [ "$CRC32_CHECKSUM" != "$EXPECTED_CRC32" ]; then
              echo "CRC32 mismatch! Expected: $EXPECTED_CRC32, Got: $CRC32_CHECKSUM"
              exit 1
            fi

      - name: Create Mount Point
        run: mkdir -p ${{ github.workspace }}/download/mnt/iso

      - name: Mount ISO and Extract Files
        run: |
          ISO_FILE=$(find ${{ github.workspace }}/download -name "*.iso" -type f | head -n 1)
          trap 'fusermount -u ${{ github.workspace }}/download/mnt/iso' EXIT
          if ! fuseiso "$ISO_FILE" ${{ github.workspace }}/download/mnt/iso; then
            echo "Failed to mount the ISO file."
            exit 1
          fi

          echo "Mounted ISO contents:"
          find ${{ github.workspace }}/download/mnt/iso

          mkdir -p ${{ github.workspace }}/download/extracted_files
          cp -r ${{ github.workspace }}/download/mnt/iso/* ${{ github.workspace }}/download/extracted_files/

          echo "Extracted files before filtering:"
          find ${{ github.workspace }}/download/extracted_files

      - name: Filter and Process Files
        id: filter_files
        run: |
          chmod -R 755 /home/runner/work/Hl/Hl/download/extracted_files
          echo "Filtering extracted files extensions"

          # Ensure directory exists
          if [ ! -d "${{ github.workspace }}/download/extracted_files" ]; then
            echo "Directory extracted_files does not exist."
            exit 1
          fi

          find "${{ github.workspace }}/download/extracted_files" -type f \( -name "*.dll" -o -name "*.emu" -o -name "*.ini" \) -exec mv {} "${{ github.workspace }}/download/extracted_files/" \;

          # Check if files exist after moving
          DLL_FILES=$(find "${{ github.workspace }}/download/extracted_files" -maxdepth 1 -type f -name "*.dll")
          EMU_FILES=$(find "${{ github.workspace }}/download/extracted_files" -maxdepth 1 -type f -name "*.emu")
          INI_FILES=$(find "${{ github.workspace }}/download/extracted_files" -maxdepth 1 -type f -name "*.ini")

          if [ -z "$DLL_FILES" ] && [ -z "$EMU_FILES" ] && [ -Z "$INI_FILES" ]; then
            echo "No .dll or .emu or .ini files found."
            echo "upload_files=false" >> $GITHUB_ENV
          else
            echo "DLL files found:"
            echo "$DLL_FILES"

            echo "EMU files found:"
            echo "$EMU_FILES"

            echo "INI files found:"
            echo "$INI_FILES"

            echo "upload_files=true" >> $GITHUB_ENV
          fi

      - name: Upload to GitHub Releases
        if: env.upload_files == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v32"
          files: |
            ${{ github.workspace }}/download/extracted_files/*.dll
            ${{ github.workspace }}/download/extracted_files/*.emu
            ${{ github.workspace }}/download/extracted_files/*.ini
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
