name: Download and Extract ISO Files
on:
  workflow_dispatch:
    inputs:
      iso_url:
        description: 'URL of the ISO file to download'
        required: true

permissions:
  contents: write  # Required for uploading files to GitHub Releases
  packages: write  # Optional, if you're using GitHub Packages

jobs:
  download_and_extract:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 p7zip-full fuseiso

      - name: Download ISO
        run: |
          aria2c "${{ github.event.inputs.iso_url }}"
          echo "Downloaded ISO files:"
          find . -name "*.iso"

      - name: Create Mount Point
        run: mkdir -p ${{ github.workspace }}/mnt/iso

      - name: Mount ISO and Extract Files
        run: |
          # Mount the ISO file
          fuseiso *.iso ${{ github.workspace }}/mnt/iso
          echo "Mounted ISO contents:"
          find ${{ github.workspace }}/mnt/iso

          # Create a directory for extracted files
          mkdir -p extracted_files

          # Copy all files from the mounted ISO to extracted_files directory
          cp ${{ github.workspace }}/mnt/iso/* extracted_files/
          echo "Extracted files before filtering:"
          find extracted_files

          # Extract only .dll and .emu files
          7z e extracted_files/*.dll extracted_files/*.emu || true

          echo "Extracted .dll and .emu files:"
          find extracted_files -name "*.dll"
          find extracted_files -name "*.emu"

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v32"
          files: |
            extracted_files/*.dll
            extracted_files/*.emu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
