name: Download and Extract ISO Files
on:
  workflow_dispatch:
    inputs:
      iso_url:
        description: 'URL of the ISO file to download'
        required: true

permissions:
  contents: write  # Required for uploading files to GitHub Releases
  packages: write  # Optional, if you're using GitHub Packages

jobs:
  download_and_extract:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 p7zip-full fuseiso

      - name: Download ISO
        run: aria2c "${{ github.event.inputs.iso_url }}"

      - name: Create Mount Point
        run: mkdir -p /mnt/iso

      - name: Mount ISO and Extract Files
        run: |
          fuseiso *.iso /mnt/iso
          mkdir -p extracted_files
          cp /mnt/iso/* extracted_files/
          7z e extracted_files/*.dll extracted_files/*.emu

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tag_name: "v32"
            extracted_files/*.dll
            extracted_files/*.emu
