name: inside archive
on:
  workflow_dispatch:
    inputs:
      upl:
        description: 'URL file'
        required: true
        type: string

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: upd
        run: |
          sudo apt-get update
      - name: cache apt
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: aria2 p7zip-full p7zip-rar
          version: 1.0
      - name: download
        run: |
          aria2c -d dloa '${{ inputs.upl }}'
      - name: unzip
        working-directory: ./dloa
        run: |
          7z x l *
          echo "CRC-32: $(crc32 *)"
