name: Install PowerShell and Run Script

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PowerShell 7+
        run: |
          Invoke-WebRequest -Uri https://github.com/PowerShell/PowerShell/releases/tag/v7.4.6/download/PowerShell-7.4.6-win-x64.msi -OutFile pwsh.msi
          Start-Process msiexec.exe -ArgumentList '/i pwsh.msi /quiet /norestart' -NoNewWindow -Wait

      - name: Clone WSAPackagingTool repository
        run: git clone https://github.com/MlgmXyysd/WSAPackagingTool.git

      - name: Download your file
        run: |
          # Замените URL на URL вашего файла
          Invoke-WebRequest -Uri "https://example.com/yourfile" -OutFile "WSAPackagingTool/unpack.cmd"

      - name: Run unpack.cmd
        run: |
          cd WSAPackagingTool
          .\unpack.cmd yourfile
